services:
  moodle_escola_a:
    image: w3soft/moodle:2026.06.1-local
    container_name: moodle_escola_a
    restart: unless-stopped
    env_file:
      - ./secrets/escola-a.local.env
    volumes:
      - moodledata_escola_a:/var/www/moodledata
    networks:
      - moodle_net
    cpus: "1.0"
    mem_limit: 1.5g
    mem_reservation: 512m

  moodle_escola_b:
    image: w3soft/moodle:2026.06.1-local
    container_name: moodle_escola_b
    restart: unless-stopped
    env_file:
      - ./secrets/escola-b.local.env
    volumes:
      - moodledata_escola_b:/var/www/moodledata
    networks:
      - moodle_net
    cpus: "1.0"
    mem_limit: 1.5g
    mem_reservation: 512m

  moodle_escola_c:
    image: w3soft/moodle:2026.06.1-local
    container_name: moodle_escola_c
    restart: unless-stopped
    env_file:
      - ./secrets/escola-c.local.env
    volumes:
      - moodledata_escola_c:/var/www/moodledata
    networks:
      - moodle_net
    cpus: "1.0"
    mem_limit: 1.5g
    mem_reservation: 512m
  moodle_escola_d:
    image: w3soft/moodle:2026.06.1-local
    container_name: moodle_escola_d
    restart: unless-stopped
    env_file:
      - ./secrets/escola-d.local.env
    volumes:
      - moodledata_escola_d:/var/www/moodledata
    networks:
      - moodle_net
    cpus: "1.0"
    mem_limit: 1.5g
    mem_reservation: 512m
  moodle_escola_e:
    image: w3soft/moodle:2026.06.1-local
    container_name: moodle_escola_e
    restart: unless-stopped
    env_file:
      - ./secrets/escola-e.local.env
    volumes:
      - moodledata_escola_e:/var/www/moodledata
    networks:
      - moodle_net
    cpus: "1.0"
    mem_limit: 1.5g
    mem_reservation: 512m
  moodle_escola_f:
    image: w3soft/moodle:2026.06.1-local
    container_name: moodle_escola_f
    restart: unless-stopped
    env_file:
      - ./secrets/escola-f.local.env
    volumes:
      - moodledata_escola_f:/var/www/moodledata
    networks:
      - moodle_net
    cpus: "1.0"
    mem_limit: 1.5g
    mem_reservation: 512m
volumes:
  moodledata_escola_a:
    name: moodledata_escola_a
  moodledata_escola_b:
    name: moodledata_escola_b

  moodledata_escola_c:
    name: moodledata_escola_c
  moodledata_escola_d:
    name: moodledata_escola_d
  moodledata_escola_e:
    name: moodledata_escola_e
  moodledata_escola_f:
    name: moodledata_escola_f
networks:
  moodle_net:
    external: true
