services:
  db:
    image: mariadb:10.11
    container_name: moodle_db
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: moodle
      MARIADB_USER: moodle
      MARIADB_PASSWORD: moodlepass
      MARIADB_ROOT_PASSWORD: rootpass
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb_file_per_table=1
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - moodle_net
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 -uroot -p$${MARIADB_ROOT_PASSWORD} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  moodle:
    image: w3soft/moodle:2026.07.1-local
    build:
      context: ./moodle
    container_name: moodle_app
    restart: unless-stopped
    env_file:
      - ./secrets/local.env
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - moodledata:/var/www/moodledata
    networks:
      - moodle_net

  # Este serviço será executado uma vez por minuto e distribuirá a carga
  # entre as diferentes instâncias de moodle. Essa funcionalidade está descrita
  # no arquivo docs/passo-08-cron-centralizado.md
  #
  # cron:
  #   image: w3soft/moodle:2026.07.1-local
  #   container_name: moodle_cron
  #   restart: unless-stopped
  #   env_file:
  #     - ./secrets/local.env
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   volumes:
  #     - moodledata:/var/www/moodledata
  #   command: >
      # sh -c "while true; do php /var/www/html/admin/cli/cron.php; sleep 60; done"
  #   networks:
  #     - moodle_net

volumes:
  db_data:
  moodledata:

networks:
  moodle_net:
    driver: bridge
